import { Footer } from '@/components/shared/footer'
import { PageHero } from '@/components/shared/page-hero'

const entries = [
  { number: '01', category: 'Perspective', title: 'The quiet power of a long view', date: 'May 18, 2026', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bahamas-jjLXXo7pomxRIWXqqWOewqlMBDZih2.jpg', excerpt: 'The most meaningful work rarely announces itself all at once. It gathers strength through patience, attention, and a willingness to keep going.' },
  { number: '02', category: 'Enterprise', title: 'Building bridges across borders', date: 'April 02, 2026', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/img-20191021-wa0015%20%281%29-7vj5mSHble7tL9auwwio5hJ1swTZZy.jpg', excerpt: 'When people and places connect with intention, geography stops being a limit and becomes a source of possibility.' },
  { number: '03', category: 'Legacy', title: 'What does progress really mean?', date: 'February 11, 2026', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lord-Neil-Gibson-and-Erwin-Contreras%20%281%29-5aV1UIGgH3a1YEvlBwRqe9jWHIk7zu.png', excerpt: 'Growth matters, but the better question is what that growth makes possible for people who come after us.' },
]

export function BlogPage() {
  return <><PageHero active="journal" eyebrow="The journal" title={<>Thoughts in<br /><em className="text-[var(--gold)]">motion.</em></>} identity="Notes on enterprise · philanthropy · place" subtitle="The patient work of building a useful future." primaryAction={{ href: '#entries', label: 'Browse the journal ↓' }} secondaryAction={{ href: '/about', label: 'Read the story' }} sideLabel="Field notes" sideValue="Ideas · Action · Legacy" /><main id="entries" className="bg-[var(--paper)] px-5 py-20 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-7xl">{entries.map((entry) => <article key={entry.number} className="grid gap-8 border-t border-black/15 py-10 md:grid-cols-[.18fr_.95fr_1.2fr] md:items-center md:gap-10 md:py-14"><div><p className="font-serif text-4xl text-[var(--gold-deep)]">{entry.number}</p><p className="mt-3 text-[10px] uppercase tracking-[.18em] text-[var(--muted-ink)]">{entry.category}</p></div><div className="overflow-hidden rounded-2xl"><img src={entry.image} alt="" className="aspect-[1.5] w-full object-cover grayscale-[.1] transition duration-700 hover:scale-105" /></div><div><p className="text-xs uppercase tracking-[.16em] text-[var(--muted-ink)]">{entry.date}</p><h2 className="mt-4 max-w-lg font-serif text-4xl leading-[.98] tracking-tight text-[var(--ink)] sm:text-5xl">{entry.title}</h2><p className="mt-5 max-w-md text-sm leading-7 text-[var(--muted-ink)]">{entry.excerpt}</p><button type="button" className="mt-7 rounded-full border border-[var(--ink)] px-5 py-3 text-xs font-semibold uppercase tracking-[.16em] text-[var(--ink)] transition hover:bg-[var(--ink)] hover:text-white">Read entry ↗</button></div></article>)}</div></main><Footer /></>
}
